name = "ts-extracted"
version = "0.1.0"
defaultTargets = ["TS"]

[[require]]
name = "autograder"
git = "https://github.com/plclub/lean4-autograder-main"
rev = "bump-4-32-0"

[[lean_lib]]
name = "TS"

[[lean_lib]]
name = "LF"
