name = "lf-extracted"
version = "0.1.0"
defaultTargets = ["LF"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "d54dddc581e08be364c278052863524bff7a99a9"

[[lean_lib]]
name = "LF"

[[lean_lib]]
name = "SFLCompat"
